### ISSUE TITLE
Ambiguous package files reported

### ISSUE THREAD

**Issue by GWevroy** [tinne26/etxt#10] opened 2023-10-06 03:22 UTC
Not sure if this is something to do with my setup, but I don't think it is. I have several relatively complex Go projects on my system that build without issue. Unfortunately, try as I might I cannot get the etxt example code to build, as the mod file/s don't configure correctly. Whenever I run go mod tidy, I get the following response:

go: finding module for package github.com/hajimehoshi/ebiten/v2
go: finding module for package github.com/tinne26/fonts/liberation/lbrtserif
go: finding module for package github.com/tinne26/etxt
go: found github.com/hajimehoshi/ebiten/v2 in github.com/hajimehoshi/ebiten/v2 v2.6.1
go: found github.com/tinne26/etxt in github.com/tinne26/etxt v0.0.8
go: found github.com/tinne26/fonts/liberation/lbrtserif in github.com/tinne26/fonts/liberation/lbrtserif v0.0.0-20230317183620-0b634734e4ec
go: main.go imports
        github.com/hajimehoshi/ebiten/v2 imports
        github.com/hajimehoshi/ebiten/v2/internal/ui imports
        golang.org/x/mobile/app imports
        golang.org/x/exp/shiny/driver/gldriver: ambiguous import: found package golang.org/x/exp/shiny/driver/gldriver in multiple modules:
        golang.org/x/exp v0.0.0-20190731235908-ec7cb31e5a56 (/home/graham/Documents/Go Programming/golib/pkg/mod/golang.org/x/exp@v0.0.0-20190731235908-ec7cb31e5a56/shiny/driver/gldriver)
        golang.org/x/exp/shiny v0.0.0-20230817173708-d852ddb80c63 (/home/graham/Documents/Go Programming/golib/pkg/mod/golang.org/x/exp/shiny@v0.0.0-20230817173708-d852ddb80c63/driver/gldriver)
go: main.go imports
        github.com/hajimehoshi/ebiten/v2 imports
        github.com/hajimehoshi/ebiten/v2/internal/ui imports
        golang.org/x/mobile/app imports
        golang.org/x/exp/shiny/screen: ambiguous import: found package golang.org/x/exp/shiny/screen in multiple modules:
        golang.org/x/exp v0.0.0-20190731235908-ec7cb31e5a56 (/home/graham/Documents/Go Programming/golib/pkg/mod/golang.org/x/exp@v0.0.0-20190731235908-ec7cb31e5a56/shiny/screen)
        golang.org/x/exp/shiny v0.0.0-20230817173708-d852ddb80c63 (/home/graham/Documents/Go Programming/golib/pkg/mod/golang.org/x/exp/shiny@v0.0.0-20230817173708-d852ddb80c63/screen)

Note the complaint about ambiguous imports. I have even tried deleting these packages out of my pkg directory, but they both immediately return when I run go mod tidy. So they must not be legacy packages, but rather are unique to etxt, and then  my system is unable to determine which package it should be using for certain resources.

**Comment by GWevroy** [comment] 2023-10-06 03:24
To clarify, I am running the latest version of Go:
go version go1.21.1 linux/amd64

This is a Linux machine, and I have already been using Ebiten extensively on it without issue.

**Comment by tinne26** [comment] 2023-10-06 16:24
Ok. Actually, I'm not sure I understand what's your exact setup, if you cloned the project or what did you do, but I think the issue is from the ebitengine versions.

Hajime Hoshi mentioned this not long ago (with the release of v2.6.0):
> [...] gomobile [...] switched the dependency from golang.org/x/exp to golang.org/x/exp/shiny, and such a nested module sometimes causes troubles. Removing the line for golang.org/x/exp and running go mod tidy would solve the issue

I may have to tag a new version for v0.0.8 with the latest Ebitengine version to resolve this. It's unclear who's at fault here, honestly, and I don't know if there's some other way to bypass this.

**Comment by GWevroy** [comment] 2023-10-07 09:10
I just manually vendorized everything (IE go get to/my/local/folder). I am using the latest and greatest of everything (Go, ebiten V2 and of course your libraries.

I'm at a loss myself in terms of what the root cause of this is (is it me/you/Hajime Hoshi). I take some small comfort that Hajime has seen this before. No rush as I have plenty other things I can keep working on, but I'll keep a watchful eye out for any news or updates. Let me know if I can be of assistance (test etc.) in this regard

**Comment by tinne26** [comment] 2023-10-07 12:46
The latest stable etxt version is etxt v0.0.8, are you using that or a v0.0.9 alpha? (so I can test on my end)

**Comment by tinne26** [comment] 2023-10-07 15:58
I have managed to reproduce, I raised the issue on <https://github.com/hajimehoshi/ebiten/issues/2803>. Notice the suggested workaround:
> Users are forced to run `go get github.com/hajimehoshi/ebiten/v2` manually first in order to avoid the problem, as running `go mod tidy` directly will fail.

**Comment by GWevroy** [comment] 2023-10-09 04:40
ok, used the workaround as per above, and I think I no longer have this error anymore (went through the process twice actually). go mod tidy completes without errors. I do see though that in my go.mod file it's pointing to version 0.0.8, not your latest (0.0.9). This is causing a couple of function mismatches in terms of number of arguments passed.

![go mod file](https://github.com/tinne26/etxt/assets/32412266/fe16144c-2c9d-427e-bcc1-c6fceeb653ac)

![attempt at build fails](https://github.com/tinne26/etxt/assets/32412266/1a749594-d26c-4b37-9ce5-a74569953f02)

**Comment by GWevroy** [comment] 2023-10-09 04:41
I suspect this just means your example code needs to be modified slightly to suit the latest version of your library.

**Comment by GWevroy** [comment] 2023-10-09 05:01
Yep, just tried manually deleting the library out of my systems and then ran go get github.com/tinne26/etxt. It installed version 0.0.8 once again.

**Comment by tinne26** [comment] 2023-10-09 06:22
Version v0.0.8 is the last stable version; v0.0.9 versions are still alpha, so using go get without the explicit alpha version will direct to v0.0.8, as it should be. Please refer to <https://github.com/tinne26/etxt/tree/v0.0.8> for documentation and so on.

**Comment by GWevroy** [comment] 2023-10-09 19:45
thanks for the response. FYI, I had tried to force go to get version 0.0.9 (which didn't work as I didn't have the "-alpha.6" suffix. I didn't see that in the documentation, sorry. I think I will carry on with other work and check back at a later date once you have had a chance to fully qualify version 0.0.9 and declare it a stable release. No rush, I have plenty other software functionality to work on.

**Comment by tinne26** [comment] 2023-10-09 20:30
Since there's not much more for me to do here and etxt v0.0.9 will depend on an Ebitengine version unaffected by this dependency ambiguity, let's close the issue. If there's anything else, feel free to open a discussion or drop by Ebitengine's discord.

**Closed by tinne26** 2023-10-09 20:30 UTC
